// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFlGE4VooegKuoYz61X83lvkTBOGpO1k',
    appId: '1:250404242314:web:918e42cceaf79089f33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    authDomain: 'teenhelper-93c4e.firebaseapp.com',
    storageBucket: 'teenhelper-93c4e.appspot.com',
    measurementId: 'G-SBKJN02LGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClE0dK3t0HV1ymzSFQv4fAaS-ckF0etVA',
    appId: '1:250404242314:android:eee46922b8d23faef33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    storageBucket: 'teenhelper-93c4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84mm9h4vSVroF3WSI7VKjsu2Ks4k_mpE',
    appId: '1:250404242314:ios:0df23a3c09196591f33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    storageBucket: 'teenhelper-93c4e.appspot.com',
    androidClientId: '250404242314-o0e1gmv25d4h70jnv0jtudcns0k05d73.apps.googleusercontent.com',
    iosClientId: '250404242314-d6ma5mmhrjdfqeitiiabng0si4r8fo1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificataion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84mm9h4vSVroF3WSI7VKjsu2Ks4k_mpE',
    appId: '1:250404242314:ios:0df23a3c09196591f33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    storageBucket: 'teenhelper-93c4e.appspot.com',
    androidClientId: '250404242314-o0e1gmv25d4h70jnv0jtudcns0k05d73.apps.googleusercontent.com',
    iosClientId: '250404242314-d6ma5mmhrjdfqeitiiabng0si4r8fo1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificataion',
  );
}
