// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClE0dK3t0HV1ymzSFQv4fAaS-ckF0etVA',
    appId: '1:250404242314:android:7c078502a77d5fe7f33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    storageBucket: 'teenhelper-93c4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84mm9h4vSVroF3WSI7VKjsu2Ks4k_mpE',
    appId: '1:250404242314:ios:1454a816ea3570dbf33e73',
    messagingSenderId: '250404242314',
    projectId: 'teenhelper-93c4e',
    storageBucket: 'teenhelper-93c4e.appspot.com',
    androidClientId: '250404242314-o0e1gmv25d4h70jnv0jtudcns0k05d73.apps.googleusercontent.com',
    iosClientId: '250404242314-rth8tsa1vc8gd2il2abmk64jk6pcuo7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.google',
  );
}
